export interface SpecialtyDefinition {
  number?: number;
  id: string;
  nameEn: string;
  nameHi: string;
  mainlyHandlesEn: string;
  mainlyHandlesHi?: string;
  category: 
    | "Emergency & Critical Care"
    | "Medical Specialties"
    | "Surgical Specialties"
    | "Diagnostic & Imaging"
    | "Pathology & Laboratory"
    | "Maternal, Fetal & Reproductive"
    | "Rehabilitation & Allied Health"
    | "Preventive & Public Health";
  room: string;
  counter: string;
  doctorEn: string;
  doctorHi: string;
  baseWait: number;
}

export const ALL_HOSPITAL_SPECIALTIES: SpecialtyDefinition[] = [
  // ── Core OPD & Emergency (1–33) ──
  {
    number: 1,
    id: "emergency_trauma",
    nameEn: "Emergency & Trauma",
    nameHi: "आपातकालीन एवं ट्रॉमा विभाग",
    mainlyHandlesEn: "Acute life-threatening emergencies, severe accidents, trauma, resuscitations",
    category: "Emergency & Critical Care",
    room: "Room 01 (Trauma Bay)",
    counter: "Counter ER-01",
    doctorEn: "Dr. Vikram Singh (Chief Trauma Officer)",
    doctorHi: "डॉ. विक्रम सिंह (मुख्य आपातकालीन अधिकारी)",
    baseWait: 0,
  },
  {
    number: 2,
    id: "cardiology",
    nameEn: "Cardiology",
    nameHi: "हृदय रोग विभाग (Cardiology)",
    mainlyHandlesEn: "Heart diseases, chest pain, palpitations, hypertension, arrhythmias",
    category: "Medical Specialties",
    room: "Room 102 (Cardio OPD)",
    counter: "Counter 02",
    doctorEn: "Dr. Ananya Sharma (Cardiologist)",
    doctorHi: "डॉ. अनन्या शर्मा (हृदय रोग विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 3,
    id: "pulmonology",
    nameEn: "Pulmonology",
    nameHi: "श्वसन व फेफड़ा रोग विभाग (Pulmonology)",
    mainlyHandlesEn: "Lungs, asthma, COPD, chronic cough, breathing difficulty, tuberculosis",
    category: "Medical Specialties",
    room: "Room 104 (Chest & Respiratory)",
    counter: "Counter 04",
    doctorEn: "Dr. Arvind Mehta (Pulmonologist)",
    doctorHi: "डॉ. अरविंद मेहता (श्वसन रोग विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 4,
    id: "gastroenterology",
    nameEn: "Gastroenterology",
    nameHi: "पेट व पाचन रोग विभाग (Gastroenterology)",
    mainlyHandlesEn: "Stomach, intestines, liver, gallbladder, acidity, jaundice, ulcers",
    category: "Medical Specialties",
    room: "Room 106 (Gastro & Liver)",
    counter: "Counter 06",
    doctorEn: "Dr. Priya Deshmukh (Gastroenterologist)",
    doctorHi: "डॉ. प्रिया देशमुख (पेट व यकृत रोग विशेषज्ञ)",
    baseWait: 12,
  },
  {
    number: 5,
    id: "neurology",
    nameEn: "Neurology",
    nameHi: "मस्तिष्क व तंत्रिका रोग विभाग (Neurology)",
    mainlyHandlesEn: "Brain, nerves, stroke, seizures, migraine, tremors, neuropathy",
    category: "Medical Specialties",
    room: "Room 108 (Neuro OPD)",
    counter: "Counter 08",
    doctorEn: "Dr. Rajesh Iyer (Neurologist)",
    doctorHi: "डॉ. राजेश अय्यर (मस्तिष्क रोग विशेषज्ञ)",
    baseWait: 20,
  },
  {
    number: 6,
    id: "orthopedics",
    nameEn: "Orthopedics",
    nameHi: "हड्डी व जोड़ रोग विभाग (Orthopedics)",
    mainlyHandlesEn: "Bones, joints, fractures, arthritis, back/knee pain, spine alignment",
    category: "Surgical Specialties",
    room: "Room 110 (Bone & Joint Clinic)",
    counter: "Counter 10",
    doctorEn: "Dr. Suresh Patel (Orthopedic Surgeon)",
    doctorHi: "डॉ. सुरेश पटेल (अस्थि रोग विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 7,
    id: "ent",
    nameEn: "ENT",
    nameHi: "कान, नाक व गला विभाग (ENT)",
    mainlyHandlesEn: "Ear infections, hearing loss, sinusitis, throat pain, tonsils, vertigo",
    category: "Surgical Specialties",
    room: "Room 112 (Ear, Nose & Throat)",
    counter: "Counter 12",
    doctorEn: "Dr. Neha Verma (ENT Specialist)",
    doctorHi: "डॉ. नेहा वर्मा (ईएनटी विशेषज्ञ)",
    baseWait: 8,
  },
  {
    number: 8,
    id: "urology",
    nameEn: "Urology",
    nameHi: "मूत्र रोग विभाग (Urology)",
    mainlyHandlesEn: "Kidney stones, urinary infections, prostate, bladder, male urinary health",
    category: "Surgical Specialties",
    room: "Room 114 (Uro & Renal Clinic)",
    counter: "Counter 14",
    doctorEn: "Dr. Alok Gupta (Urologist)",
    doctorHi: "डॉ. आलोक गुप्ता (मूत्र रोग विशेषज्ञ)",
    baseWait: 14,
  },
  {
    number: 9,
    id: "dermatology",
    nameEn: "Dermatology",
    nameHi: "त्वचा रोग विभाग (Dermatology)",
    mainlyHandlesEn: "Skin rashes, eczema, psoriasis, fungal infections, allergies, hair/nail issues",
    category: "Medical Specialties",
    room: "Room 116 (Skin Clinic)",
    counter: "Counter 16",
    doctorEn: "Dr. Kavita Nair (Dermatologist)",
    doctorHi: "डॉ. कविता नायर (त्वचा रोग विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 10,
    id: "general_medicine",
    nameEn: "General Medicine",
    nameHi: "सामान्य चिकित्सा विभाग (General Medicine)",
    mainlyHandlesEn: "Fever, infections, diabetes, hypertension, fatigue, comprehensive primary health",
    category: "Medical Specialties",
    room: "Room 101 (Primary Care OPD)",
    counter: "Counter 01",
    doctorEn: "Dr. Sunita Rao (Senior Physician)",
    doctorHi: "डॉ. सुनीता राव (वरिष्ठ चिकित्सक)",
    baseWait: 10,
  },
  {
    number: 11,
    id: "general_surgery",
    nameEn: "General Surgery",
    nameHi: "सामान्य शल्य चिकित्सा विभाग (General Surgery)",
    mainlyHandlesEn: "Hernia, appendicitis, cysts, abdominal surgery, wound management",
    category: "Surgical Specialties",
    room: "Room 118 (Surgical OPD)",
    counter: "Counter 18",
    doctorEn: "Dr. Harish Chandra (General Surgeon)",
    doctorHi: "डॉ. हरीश चंद्र (शल्य चिकित्सक)",
    baseWait: 15,
  },
  {
    number: 12,
    id: "ophthalmology",
    nameEn: "Ophthalmology",
    nameHi: "नेत्र रोग विभाग (Ophthalmology)",
    mainlyHandlesEn: "Eye pain, cataracts, vision problems, glaucoma, eye redness/injuries",
    category: "Surgical Specialties",
    room: "Room 120 (Eye OPD)",
    counter: "Counter 20",
    doctorEn: "Dr. Madhavan Pillai (Eye Specialist)",
    doctorHi: "डॉ. माधवन पिल्लई (नेत्र रोग विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 13,
    id: "pediatrics",
    nameEn: "Pediatrics",
    nameHi: "बाल रोग विभाग (Pediatrics)",
    mainlyHandlesEn: "Infant and child health, pediatric infections, growth, immunizations",
    category: "Medical Specialties",
    room: "Room 122 (Child Health OPD)",
    counter: "Counter 22",
    doctorEn: "Dr. Shalini Kapoor (Pediatrician)",
    doctorHi: "डॉ. शालिनी कपूर (बाल रोग विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 14,
    id: "gynecology_obstetrics",
    nameEn: "Obstetrics & Gynecology",
    nameHi: "प्रसूति एवं स्त्री रोग विभाग (OB-GYN)",
    mainlyHandlesEn: "Pregnancy care, delivery, menstrual health, pelvic disorders, uterine care",
    category: "Maternal, Fetal & Reproductive",
    room: "Room 124 (Women Health Clinic)",
    counter: "Counter 24",
    doctorEn: "Dr. Rekha Bhatt (OB-GYN Specialist)",
    doctorHi: "डॉ. रेखा भट्ट (स्त्री रोग विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 15,
    id: "psychiatry",
    nameEn: "Psychiatry",
    nameHi: "मनोचिकित्सा विभाग (Psychiatry)",
    mainlyHandlesEn: "Mental health, depression, anxiety, mood disorders, sleep disturbance, psychosis",
    category: "Medical Specialties",
    room: "Room 126 (Mind & Behavioral OPD)",
    counter: "Counter 26",
    doctorEn: "Dr. Anand Joshi (Psychiatrist)",
    doctorHi: "डॉ. आनंद जोशी (मनोचिकित्सक)",
    baseWait: 15,
  },
  {
    number: 16,
    id: "endocrinology",
    nameEn: "Endocrinology",
    nameHi: "हार्मोन व मधुमेह रोग विभाग (Endocrinology)",
    mainlyHandlesEn: "Diabetes, thyroid disorders, hormonal imbalance, metabolic disorders",
    category: "Medical Specialties",
    room: "Room 128 (Endocrine Clinic)",
    counter: "Counter 28",
    doctorEn: "Dr. Meenakshi Sundaram (Endocrinologist)",
    doctorHi: "डॉ. मीनाक्षी सुंदरम (हार्मोन रोग विशेषज्ञ)",
    baseWait: 12,
  },
  {
    number: 17,
    id: "nephrology",
    nameEn: "Nephrology",
    nameHi: "गुर्दा / किडनी रोग विभाग (Nephrology)",
    mainlyHandlesEn: "Kidney failure, dialysis, proteinuria, electrolyte imbalances",
    category: "Medical Specialties",
    room: "Room 130 (Kidney & Dialysis OPD)",
    counter: "Counter 30",
    doctorEn: "Dr. Deepak Varma (Nephrologist)",
    doctorHi: "डॉ. दीपक वर्मा (गुर्दा रोग विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 18,
    id: "oncology",
    nameEn: "Oncology",
    nameHi: "कैंसर रोग विभाग (Oncology)",
    mainlyHandlesEn: "Cancer diagnosis, chemotherapy, tumor staging, oncologic consultations",
    category: "Medical Specialties",
    room: "Room 132 (Oncology Clinic)",
    counter: "Counter 32",
    doctorEn: "Dr. Rajiv Singhal (Medical Oncologist)",
    doctorHi: "डॉ. राजीव सिंघल (कैंसर विशेषज्ञ)",
    baseWait: 18,
  },
  {
    number: 19,
    id: "rheumatology",
    nameEn: "Rheumatology",
    nameHi: "गठिया व ऑटोइम्यून रोग विभाग (Rheumatology)",
    mainlyHandlesEn: "Rheumatoid arthritis, lupus, autoimmune connective tissue disorders",
    category: "Medical Specialties",
    room: "Room 134 (Rheumatology OPD)",
    counter: "Counter 34",
    doctorEn: "Dr. Vandana Saxena (Rheumatologist)",
    doctorHi: "डॉ. वंदना सक्सेना (गठिया रोग विशेषज्ञ)",
    baseWait: 14,
  },
  {
    number: 20,
    id: "hematology",
    nameEn: "Hematology",
    nameHi: "रक्त रोग विभाग (Hematology)",
    mainlyHandlesEn: "Anemia, blood clotting disorders, leukemia, thalassemia, platelet issues",
    category: "Medical Specialties",
    room: "Room 136 (Blood Disorders OPD)",
    counter: "Counter 36",
    doctorEn: "Dr. Pankaj Banerjee (Hematologist)",
    doctorHi: "डॉ. पंकज बनर्जी (रक्त रोग विशेषज्ञ)",
    baseWait: 12,
  },

  // ── Specialty List (34–75 from User Specifications) ──
  {
    number: 34,
    id: "critical_care_icu",
    nameEn: "Critical Care / ICU Medicine",
    nameHi: "गहन चिकित्सा / आईसीयू (Critical Care / ICU)",
    mainlyHandlesEn: "Life-threatening and critically ill patients",
    category: "Emergency & Critical Care",
    room: "ICU Complex (Tower B, Level 2)",
    counter: "Counter ICU-01",
    doctorEn: "Dr. Manish Tandon (Intensivist)",
    doctorHi: "डॉ. मनीष टंडन (गहन चिकित्सा विशेषज्ञ)",
    baseWait: 0,
  },
  {
    number: 35,
    id: "anesthesiology",
    nameEn: "Anesthesiology",
    nameHi: "एनेस्थिसियोलॉजी विभाग (Anesthesiology)",
    mainlyHandlesEn: "Anesthesia, perioperative and pain management",
    category: "Surgical Specialties",
    room: "OT Pre-Op Suite (Level 3)",
    counter: "Counter AN-01",
    doctorEn: "Dr. Sanjeev Kaul (Chief Anesthesiologist)",
    doctorHi: "डॉ. संजीव कौल (मुख्य एनेस्थीसिया विशेषज्ञ)",
    baseWait: 5,
  },
  {
    number: 36,
    id: "pain_medicine",
    nameEn: "Pain Medicine",
    nameHi: "दर्द निवारण चिकित्सा (Pain Medicine)",
    mainlyHandlesEn: "Chronic and complex pain",
    category: "Medical Specialties",
    room: "Room 201 (Pain Clinic)",
    counter: "Counter 41",
    doctorEn: "Dr. Rohit Mathur (Pain Specialist)",
    doctorHi: "डॉ. रोहित माथुर (दर्द निवारण विशेषज्ञ)",
    baseWait: 12,
  },
  {
    number: 37,
    id: "pmr",
    nameEn: "Physical Medicine & Rehabilitation",
    nameHi: "भौतिक चिकित्सा व पुनर्वास (PMR)",
    mainlyHandlesEn: "Recovery and rehabilitation after illness/injury",
    category: "Rehabilitation & Allied Health",
    room: "Rehab Center (Ground Floor)",
    counter: "Counter PMR-01",
    doctorEn: "Dr. Smita Chawla (Physiatrist)",
    doctorHi: "डॉ. स्मिता चावला (पुनर्वास विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 38,
    id: "vascular_surgery",
    nameEn: "Vascular Surgery",
    nameHi: "संवहनी शल्य चिकित्सा (Vascular Surgery)",
    mainlyHandlesEn: "Arteries, veins and vascular diseases",
    category: "Surgical Specialties",
    room: "Room 203 (Vascular OPD)",
    counter: "Counter 43",
    doctorEn: "Dr. Nitin Kulkarni (Vascular Surgeon)",
    doctorHi: "डॉ. नितिन कुलकर्णी (संवहनी सर्जन)",
    baseWait: 15,
  },
  {
    number: 39,
    id: "plastic_surgery",
    nameEn: "Plastic & Reconstructive Surgery",
    nameHi: "प्लास्टिक व पुनर्निर्माण सर्जरी (Plastic Surgery)",
    mainlyHandlesEn: "Reconstruction, burns and tissue repair",
    category: "Surgical Specialties",
    room: "Room 205 (Cosmetic & Burn Suite)",
    counter: "Counter 45",
    doctorEn: "Dr. Farhan Qureshi (Plastic Surgeon)",
    doctorHi: "डॉ. फरहान कुरैशी (प्लास्टिक सर्जन)",
    baseWait: 15,
  },
  {
    number: 40,
    id: "pediatric_surgery",
    nameEn: "Pediatric Surgery",
    nameHi: "बाल शल्य चिकित्सा (Pediatric Surgery)",
    mainlyHandlesEn: "Surgical conditions in children",
    category: "Surgical Specialties",
    room: "Room 207 (Pediatric Surgery OPD)",
    counter: "Counter 47",
    doctorEn: "Dr. Geeta Nair (Pediatric Surgeon)",
    doctorHi: "डॉ. गीता नायर (बाल शल्य चिकित्सक)",
    baseWait: 12,
  },
  {
    number: 41,
    id: "colorectal_surgery",
    nameEn: "Colorectal Surgery",
    nameHi: "कोलोरेक्टल सर्जरी (Colorectal Surgery)",
    mainlyHandlesEn: "Colon, rectum and anus",
    category: "Surgical Specialties",
    room: "Room 209 (Proctology Clinic)",
    counter: "Counter 49",
    doctorEn: "Dr. Hemant Bhargava (Colorectal Surgeon)",
    doctorHi: "डॉ. हेमंत भार्गव (कोलोरेक्टल सर्जन)",
    baseWait: 15,
  },
  {
    number: 42,
    id: "breast_surgery",
    nameEn: "Breast Surgery",
    nameHi: "स्तन रोग व शल्य चिकित्सा (Breast Surgery)",
    mainlyHandlesEn: "Breast diseases and surgery",
    category: "Surgical Specialties",
    room: "Room 211 (Breast Care Clinic)",
    counter: "Counter 51",
    doctorEn: "Dr. Shilpa Ghosh (Oncoplastic Breast Surgeon)",
    doctorHi: "डॉ. शिल्पा घोष (स्तन शल्य चिकित्सक)",
    baseWait: 14,
  },
  {
    number: 43,
    id: "transplant_surgery",
    nameEn: "Transplant Surgery",
    nameHi: "प्रत्यारोपण शल्य चिकित्सा (Transplant Surgery)",
    mainlyHandlesEn: "Organ transplantation",
    category: "Surgical Specialties",
    room: "Transplant OPD (Tower A, Level 4)",
    counter: "Counter TX-01",
    doctorEn: "Dr. Subhash Sethi (Transplant Surgeon)",
    doctorHi: "डॉ. सुभाष सेठी (प्रत्यारोपण विशेषज्ञ)",
    baseWait: 20,
  },
  {
    number: 44,
    id: "bariatric_surgery",
    nameEn: "Bariatric / Metabolic Surgery",
    nameHi: "बेरियाट्रिक व मेटाबॉलिक सर्जरी (Bariatric Surgery)",
    mainlyHandlesEn: "Surgical treatment of severe obesity/metabolic disease",
    category: "Surgical Specialties",
    room: "Room 213 (Metabolic Clinic)",
    counter: "Counter 53",
    doctorEn: "Dr. Tarun Grover (Bariatric Surgeon)",
    doctorHi: "डॉ. तरुण ग्रोवर (बेरियाट्रिक सर्जन)",
    baseWait: 15,
  },
  {
    number: 45,
    id: "maxillofacial_surgery",
    nameEn: "Maxillofacial Surgery",
    nameHi: "मैक्सिलोफेशियल सर्जरी (Maxillofacial Surgery)",
    mainlyHandlesEn: "Face, jaw and oral surgical conditions",
    category: "Surgical Specialties",
    room: "Room 215 (Craniofacial Suite)",
    counter: "Counter 55",
    doctorEn: "Dr. Anirudh Sen (Maxillofacial Surgeon)",
    doctorHi: "डॉ. अनिरुद्ध सेन (चेहरा व जबड़ा शल्य चिकित्सक)",
    baseWait: 15,
  },
  {
    number: 46,
    id: "spine_surgery",
    nameEn: "Spine Surgery",
    nameHi: "रीढ़ की हड्डी शल्य चिकित्सा (Spine Surgery)",
    mainlyHandlesEn: "Surgical spine conditions",
    category: "Surgical Specialties",
    room: "Room 217 (Spine Center)",
    counter: "Counter 57",
    doctorEn: "Dr. Vivek Aggarwal (Spine Surgeon)",
    doctorHi: "डॉ. विवेक अग्रवाल (स्पाइन सर्जन)",
    baseWait: 18,
  },
  {
    number: 47,
    id: "sports_medicine",
    nameEn: "Sports Medicine",
    nameHi: "स्पोर्ट्स मेडिसिन (Sports Medicine)",
    mainlyHandlesEn: "Sports injuries and musculoskeletal problems",
    category: "Medical Specialties",
    room: "Room 219 (Athletic Injury OPD)",
    counter: "Counter 59",
    doctorEn: "Dr. Karan Dixit (Sports Physician)",
    doctorHi: "डॉ. करन दीक्षित (स्पोर्ट्स विशेषज्ञ)",
    baseWait: 12,
  },
  {
    number: 48,
    id: "nuclear_medicine",
    nameEn: "Nuclear Medicine",
    nameHi: "न्यूक्लियर मेडिसिन (Nuclear Medicine)",
    mainlyHandlesEn: "Diagnosis/treatment using radioactive tracers",
    category: "Diagnostic & Imaging",
    room: "PET-CT Wing (Basement Level)",
    counter: "Counter NM-01",
    doctorEn: "Dr. Brijesh Mishra (Nuclear Physician)",
    doctorHi: "डॉ. बृजेश मिश्रा (न्यूक्लियर मेडिसिन विशेषज्ञ)",
    baseWait: 20,
  },
  {
    number: 49,
    id: "radiology",
    nameEn: "Radiology",
    nameHi: "रेडियोलॉजी व इमेजिंग (Radiology)",
    mainlyHandlesEn: "X-ray, CT, MRI, ultrasound and imaging",
    category: "Diagnostic & Imaging",
    room: "Radiology Diagnostic Complex (Level 1)",
    counter: "Counter RD-01",
    doctorEn: "Dr. Vinay Tripathi (Chief Radiologist)",
    doctorHi: "डॉ. विनय त्रिपाठी (रेडियोलॉजिस्ट)",
    baseWait: 15,
  },
  {
    number: 50,
    id: "interventional_radiology",
    nameEn: "Interventional Radiology",
    nameHi: "इंटरवेंशनल रेडियोलॉजी (Interventional Radiology)",
    mainlyHandlesEn: "Image-guided minimally invasive procedures",
    category: "Diagnostic & Imaging",
    room: "Cath Lab Suite 2",
    counter: "Counter IR-01",
    doctorEn: "Dr. Prateek Jain (Interventional Radiologist)",
    doctorHi: "डॉ. प्रतीक जैन (इंटरवेंशनल रेडियोलॉजिस्ट)",
    baseWait: 20,
  },
  {
    number: 51,
    id: "pathology",
    nameEn: "Pathology",
    nameHi: "पैथोलॉजी विभाग (Pathology)",
    mainlyHandlesEn: "Laboratory diagnosis of diseases",
    category: "Pathology & Laboratory",
    room: "Central Diagnostic Lab (Ground Floor)",
    counter: "Counter LAB-01",
    doctorEn: "Dr. Ruchira Sen (Chief Pathologist)",
    doctorHi: "डॉ. रुचिरा सेन (मुख्य पैथोलॉजिस्ट)",
    baseWait: 10,
  },
  {
    number: 52,
    id: "clinical_pathology",
    nameEn: "Clinical Pathology",
    nameHi: "क्लिनिकल पैथोलॉजी (Clinical Pathology)",
    mainlyHandlesEn: "Blood, urine and other laboratory investigations",
    category: "Pathology & Laboratory",
    room: "Specimen Collection Counter 1",
    counter: "Counter CP-01",
    doctorEn: "Dr. Sanjay Roy (Clinical Pathologist)",
    doctorHi: "डॉ. संजय रॉय (क्लिनिकल पैथोलॉजिस्ट)",
    baseWait: 5,
  },
  {
    number: 53,
    id: "anatomic_pathology",
    nameEn: "Anatomic Pathology",
    nameHi: "एनाटॉमिक पैथोलॉजी (Anatomic Pathology)",
    mainlyHandlesEn: "Tissue and biopsy diagnosis",
    category: "Pathology & Laboratory",
    room: "Histopathology Lab (Level 2)",
    counter: "Counter AP-01",
    doctorEn: "Dr. Maitreyi Sharma (Histopathologist)",
    doctorHi: "डॉ. मैत्रेयी शर्मा (बायोप्सी विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 54,
    id: "microbiology",
    nameEn: "Microbiology",
    nameHi: "माइक्रोबायोलॉजी विभाग (Microbiology)",
    mainlyHandlesEn: "Microbial infections",
    category: "Pathology & Laboratory",
    room: "Infection Diagnostics Wing",
    counter: "Counter MB-01",
    doctorEn: "Dr. Rameshwar Dutt (Microbiologist)",
    doctorHi: "डॉ. रामेश्वर दत्त (माइक्रोबायोलॉजिस्ट)",
    baseWait: 10,
  },
  {
    number: 55,
    id: "biochemistry",
    nameEn: "Biochemistry",
    nameHi: "बायोकेमिस्ट्री विभाग (Biochemistry)",
    mainlyHandlesEn: "Chemical analysis of blood/body fluids",
    category: "Pathology & Laboratory",
    room: "Automated Chemistry Lab",
    counter: "Counter BC-01",
    doctorEn: "Dr. Archana Pillai (Biochemist)",
    doctorHi: "डॉ. अर्चना पिल्लई (बायोकेमिस्ट)",
    baseWait: 10,
  },
  {
    number: 56,
    id: "genetics",
    nameEn: "Genetics / Medical Genetics",
    nameHi: "मेडिकल जेनेटिक्स (Medical Genetics)",
    mainlyHandlesEn: "Genetic and inherited disorders",
    category: "Medical Specialties",
    room: "Room 301 (Genetics OPD)",
    counter: "Counter 61",
    doctorEn: "Dr. Soumya Swaminathan (Geneticist)",
    doctorHi: "डॉ. सौम्या स्वामीनाथन (जेनेटिक्स विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 57,
    id: "clinical_genomics",
    nameEn: "Clinical Genomics",
    nameHi: "क्लिनिकल जीनोमिक्स (Clinical Genomics)",
    mainlyHandlesEn: "Genetic testing and genomic diseases",
    category: "Diagnostic & Imaging",
    room: "Genomics Research & Testing Lab",
    counter: "Counter CG-01",
    doctorEn: "Dr. Harsh Vardhan (Genomics Specialist)",
    doctorHi: "डॉ. हर्ष वर्धन (जीनोमिक्स विशेषज्ञ)",
    baseWait: 18,
  },
  {
    number: 58,
    id: "occupational_medicine",
    nameEn: "Occupational Medicine",
    nameHi: "व्यावसायिक स्वास्थ्य चिकित्सा (Occupational Medicine)",
    mainlyHandlesEn: "Work-related diseases and injuries",
    category: "Preventive & Public Health",
    room: "Room 303 (Occupational Health)",
    counter: "Counter 63",
    doctorEn: "Dr. Alok Nath (Occupational Health Physician)",
    doctorHi: "डॉ. आलोक नाथ (व्यावसायिक स्वास्थ्य विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 59,
    id: "psm",
    nameEn: "Preventive & Social Medicine",
    nameHi: "निवारक एवं सामाजिक चिकित्सा (PSM)",
    mainlyHandlesEn: "Disease prevention and population health",
    category: "Preventive & Public Health",
    room: "Community Health Center",
    counter: "Counter PSM-01",
    doctorEn: "Dr. Anita George (PSM Specialist)",
    doctorHi: "डॉ. अनीता जॉर्ज (निवारक स्वास्थ्य विशेषज्ञ)",
    baseWait: 8,
  },
  {
    number: 60,
    id: "public_health_medicine",
    nameEn: "Public Health Medicine",
    nameHi: "सार्वजनिक स्वास्थ्य चिकित्सा (Public Health)",
    mainlyHandlesEn: "Community-level disease prevention",
    category: "Preventive & Public Health",
    room: "Epidemiology & Public Health Unit",
    counter: "Counter PH-01",
    doctorEn: "Dr. Vijayaraghavan (Public Health Officer)",
    doctorHi: "डॉ. विजयाराघवन (सार्वजनिक स्वास्थ्य अधिकारी)",
    baseWait: 8,
  },
  {
    number: 61,
    id: "tropical_medicine",
    nameEn: "Tropical Medicine",
    nameHi: "उष्णकटिबंधीय चिकित्सा (Tropical Medicine)",
    mainlyHandlesEn: "Diseases common in tropical regions",
    category: "Medical Specialties",
    room: "Room 305 (Tropical Disease Unit)",
    counter: "Counter 65",
    doctorEn: "Dr. Debashish Bose (Tropical Physician)",
    doctorHi: "डॉ. देबाशीष बोस (उष्णकटिबंधीय रोग विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 62,
    id: "travel_medicine",
    nameEn: "Travel Medicine",
    nameHi: "ट्रैवल मेडिसिन व टीकाकरण (Travel Medicine)",
    mainlyHandlesEn: "Travel-related infections and health issues",
    category: "Preventive & Public Health",
    room: "Room 307 (Travel & Vaccine Clinic)",
    counter: "Counter 67",
    doctorEn: "Dr. Natasha Kohli (Travel Health Consultant)",
    doctorHi: "डॉ. नताशा कोहली (ट्रैवल हेल्थ विशेषज्ञ)",
    baseWait: 8,
  },
  {
    number: 63,
    id: "sleep_medicine",
    nameEn: "Sleep Medicine",
    nameHi: "स्लीप मेडिसिन / निद्रा रोग (Sleep Medicine)",
    mainlyHandlesEn: "Sleep disorders",
    category: "Medical Specialties",
    room: "Sleep Lab (Level 3)",
    counter: "Counter SL-01",
    doctorEn: "Dr. Ashish Manral (Somnologist)",
    doctorHi: "डॉ. आशीष मनराल (निद्रा रोग विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 64,
    id: "adolescent_medicine",
    nameEn: "Adolescent Medicine",
    nameHi: "किशोर स्वास्थ्य चिकित्सा (Adolescent Medicine)",
    mainlyHandlesEn: "Health conditions in adolescents",
    category: "Medical Specialties",
    room: "Room 309 (Teen Health Clinic)",
    counter: "Counter 69",
    doctorEn: "Dr. Ritu Chhabra (Adolescent Physician)",
    doctorHi: "डॉ. रितु छाबड़ा (किशोर स्वास्थ्य विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 65,
    id: "palliative_medicine",
    nameEn: "Palliative Medicine",
    nameHi: "उपशामक चिकित्सा (Palliative Medicine)",
    mainlyHandlesEn: "Supportive care for serious illnesses",
    category: "Medical Specialties",
    room: "Room 311 (Palliative Care Center)",
    counter: "Counter 71",
    doctorEn: "Dr. Mary Varghese (Palliative Specialist)",
    doctorHi: "डॉ. मैरी वर्गीज (उपशामक चिकित्सा विशेषज्ञ)",
    baseWait: 10,
  },
  {
    number: 66,
    id: "nuclear_cardiology",
    nameEn: "Nuclear Cardiology",
    nameHi: "न्यूक्लियर कार्डियोलॉजी (Nuclear Cardiology)",
    mainlyHandlesEn: "Specialized cardiac imaging",
    category: "Diagnostic & Imaging",
    room: "Nuclear Cardio Suite (Level 1)",
    counter: "Counter NC-01",
    doctorEn: "Dr. Tarun Majumdar (Nuclear Cardiologist)",
    doctorHi: "डॉ. तरुण मजूमदार (न्यूक्लियर कार्डियोलॉजिस्ट)",
    baseWait: 18,
  },
  {
    number: 67,
    id: "maternal_fetal_medicine",
    nameEn: "Maternal-Fetal Medicine",
    nameHi: "मातृ-भ्रूण चिकित्सा (Maternal-Fetal Medicine)",
    mainlyHandlesEn: "High-risk pregnancies",
    category: "Maternal, Fetal & Reproductive",
    room: "High-Risk Pregnancy Unit (Level 2)",
    counter: "Counter MFM-01",
    doctorEn: "Dr. Anindita Sengupta (MFM Specialist)",
    doctorHi: "डॉ. अनिंदिता सेनगुप्ता (मातृ-भ्रूण विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 68,
    id: "perinatology",
    nameEn: "Perinatology",
    nameHi: "पेरिनाटोलॉजी (Perinatology)",
    mainlyHandlesEn: "Complicated pregnancy and fetal conditions",
    category: "Maternal, Fetal & Reproductive",
    room: "Perinatal Center (Level 2)",
    counter: "Counter PN-01",
    doctorEn: "Dr. Sarita Dixit (Perinatologist)",
    doctorHi: "डॉ. सरिता दीक्षित (पेरिनाटोलॉजिस्ट)",
    baseWait: 15,
  },
  {
    number: 69,
    id: "fetal_medicine",
    nameEn: "Fetal Medicine",
    nameHi: "भ्रूण चिकित्सा (Fetal Medicine)",
    mainlyHandlesEn: "Fetal health and prenatal conditions",
    category: "Maternal, Fetal & Reproductive",
    room: "Prenatal Diagnostic Suite",
    counter: "Counter FM-01",
    doctorEn: "Dr. Kavita Rastogi (Fetal Medicine Specialist)",
    doctorHi: "डॉ. कविता रस्तोगी (भ्रूण चिकित्सा विशेषज्ञ)",
    baseWait: 15,
  },
  {
    number: 70,
    id: "andrology",
    nameEn: "Andrology",
    nameHi: "एंड्रोलॉजी / पुरुष प्रजनन स्वास्थ्य (Andrology)",
    mainlyHandlesEn: "Male reproductive health",
    category: "Maternal, Fetal & Reproductive",
    room: "Room 315 (Men's Health Clinic)",
    counter: "Counter 75",
    doctorEn: "Dr. Gaurav Singla (Andrologist)",
    doctorHi: "डॉ. गौरव सिंगला (एंड्रोलॉजिस्ट)",
    baseWait: 12,
  },
  {
    number: 71,
    id: "sexual_medicine",
    nameEn: "Sexual Medicine",
    nameHi: "यौन स्वास्थ्य चिकित्सा (Sexual Medicine)",
    mainlyHandlesEn: "Sexual and reproductive health disorders",
    category: "Maternal, Fetal & Reproductive",
    room: "Room 317 (Sexual Health Clinic)",
    counter: "Counter 77",
    doctorEn: "Dr. Sameer Parikh (Sexual Health Consultant)",
    doctorHi: "डॉ. समीर पारिख (यौन स्वास्थ्य विशेषज्ञ)",
    baseWait: 12,
  },
  {
    number: 72,
    id: "audiology",
    nameEn: "Audiology",
    nameHi: "ऑडियोलॉजी / श्रवण विकार (Audiology)",
    mainlyHandlesEn: "Hearing and balance disorders",
    category: "Rehabilitation & Allied Health",
    room: "Soundproof Hearing Lab (Level 1)",
    counter: "Counter AUD-01",
    doctorEn: "Dr. Preeti Ganguly (Audiologist)",
    doctorHi: "डॉ. प्रीति गांगुली (ऑडियोलॉजिस्ट)",
    baseWait: 10,
  },
  {
    number: 73,
    id: "speech_pathology",
    nameEn: "Speech & Language Pathology",
    nameHi: "वाणी एवं भाषा विकार चिकित्सा (Speech Pathology)",
    mainlyHandlesEn: "Speech, language and swallowing disorders",
    category: "Rehabilitation & Allied Health",
    room: "Speech Therapy Studio",
    counter: "Counter SLP-01",
    doctorEn: "Dr. Ananya Roy (Speech Pathologist)",
    doctorHi: "डॉ. अनन्या रॉय (स्पीच थेरेपिस्ट)",
    baseWait: 12,
  },
  {
    number: 74,
    id: "optometry",
    nameEn: "Optometry",
    nameHi: "ऑप्टोमेट्री / दृष्टि जांच (Optometry)",
    mainlyHandlesEn: "Vision and refractive problems",
    category: "Rehabilitation & Allied Health",
    room: "Vision Refraction Suite",
    counter: "Counter OPT-01",
    doctorEn: "Dr. Rajesh Khandelwal (Optometrist)",
    doctorHi: "डॉ. राजेश खंडेलवाल (ऑप्टोमेट्रिस्ट)",
    baseWait: 8,
  },
  {
    number: 75,
    id: "clinical_nutrition",
    nameEn: "Clinical Nutrition / Dietetics",
    nameHi: "क्लिनिकल न्यूट्रिशन व आहार विज्ञान (Dietetics)",
    mainlyHandlesEn: "Nutrition-related conditions and therapeutic diets",
    category: "Rehabilitation & Allied Health",
    room: "Room 321 (Dietetics & Nutrition)",
    counter: "Counter 81",
    doctorEn: "Dr. Pooja Makhija (Chief Clinical Nutritionist)",
    doctorHi: "डॉ. पूजा मखीजा (मुख्य आहार विशेषज्ञ)",
    baseWait: 10,
  },
];

export const SPECIALTY_MAP: Record<string, SpecialtyDefinition> = {};
ALL_HOSPITAL_SPECIALTIES.forEach((spec) => {
  SPECIALTY_MAP[spec.nameEn] = spec;
  SPECIALTY_MAP[spec.id] = spec;
});

export function getSpecialtyByName(name: string): SpecialtyDefinition | undefined {
  return SPECIALTY_MAP[name] || ALL_HOSPITAL_SPECIALTIES.find(
    s => s.nameEn.toLowerCase() === name.toLowerCase() || s.id.toLowerCase() === name.toLowerCase()
  );
}
