export interface StateInfo {
  id: string;
  name: string;
  nameHi: string;
  primaryLanguage: string;
  primaryLanguageCode: string;
  primaryLanguageNative: string;
  ttsLocale: string;
}

export const INDIAN_STATES: StateInfo[] = [
  {
    id: "national",
    name: "All India / National",
    nameHi: "अखिल भारतीय / राष्ट्रीय",
    primaryLanguage: "English / Hindi",
    primaryLanguageCode: "en",
    primaryLanguageNative: "English",
    ttsLocale: "en-IN",
  },
  {
    id: "delhi",
    name: "Delhi (NCR)",
    nameHi: "दिल्ली (एनसीआर)",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    nameHi: "महाराष्ट्र",
    primaryLanguage: "Marathi",
    primaryLanguageCode: "mr",
    primaryLanguageNative: "मराठी",
    ttsLocale: "mr-IN",
  },
  {
    id: "karnataka",
    name: "Karnataka",
    nameHi: "कर्नाटक",
    primaryLanguage: "Kannada",
    primaryLanguageCode: "kn",
    primaryLanguageNative: "ಕನ್ನಡ",
    ttsLocale: "kn-IN",
  },
  {
    id: "tamil_nadu",
    name: "Tamil Nadu",
    nameHi: "तमिलनाडु",
    primaryLanguage: "Tamil",
    primaryLanguageCode: "ta",
    primaryLanguageNative: "தமிழ்",
    ttsLocale: "ta-IN",
  },
  {
    id: "west_bengal",
    name: "West Bengal",
    nameHi: "पश्चिम बंगाल",
    primaryLanguage: "Bengali",
    primaryLanguageCode: "bn",
    primaryLanguageNative: "বাংলা",
    ttsLocale: "bn-IN",
  },
  {
    id: "gujarat",
    name: "Gujarat",
    nameHi: "गुजरात",
    primaryLanguage: "Gujarati",
    primaryLanguageCode: "gu",
    primaryLanguageNative: "ગુજરાતી",
    ttsLocale: "gu-IN",
  },
  {
    id: "punjab",
    name: "Punjab",
    nameHi: "पंजाब",
    primaryLanguage: "Punjabi",
    primaryLanguageCode: "pa",
    primaryLanguageNative: "ਪੰਜਾਬੀ",
    ttsLocale: "pa-IN",
  },
  {
    id: "kerala",
    name: "Kerala",
    nameHi: "केरल",
    primaryLanguage: "Malayalam",
    primaryLanguageCode: "ml",
    primaryLanguageNative: "മലയാളം",
    ttsLocale: "ml-IN",
  },
  {
    id: "andhra_pradesh",
    name: "Andhra Pradesh",
    nameHi: "आंध्र प्रदेश",
    primaryLanguage: "Telugu",
    primaryLanguageCode: "te",
    primaryLanguageNative: "తెలుగు",
    ttsLocale: "te-IN",
  },
  {
    id: "telangana",
    name: "Telangana",
    nameHi: "तेलंगाना",
    primaryLanguage: "Telugu",
    primaryLanguageCode: "te",
    primaryLanguageNative: "తెలుగు",
    ttsLocale: "te-IN",
  },
  {
    id: "odisha",
    name: "Odisha",
    nameHi: "ओडिशा",
    primaryLanguage: "Odia",
    primaryLanguageCode: "or",
    primaryLanguageNative: "ଓଡ଼ିଆ",
    ttsLocale: "or-IN",
  },
  {
    id: "assam",
    name: "Assam",
    nameHi: "असम",
    primaryLanguage: "Assamese",
    primaryLanguageCode: "as",
    primaryLanguageNative: "অসমীয়া",
    ttsLocale: "as-IN",
  },
  {
    id: "uttar_pradesh",
    name: "Uttar Pradesh",
    nameHi: "उत्तर प्रदेश",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "bihar",
    name: "Bihar",
    nameHi: "बिहार",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "rajasthan",
    name: "Rajasthan",
    nameHi: "राजस्थान",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "madhya_pradesh",
    name: "Madhya Pradesh",
    nameHi: "मध्य प्रदेश",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "haryana",
    name: "Haryana",
    nameHi: "हरियाणा",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "himachal_pradesh",
    name: "Himachal Pradesh",
    nameHi: "हिमाचल प्रदेश",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    nameHi: "उत्तराखंड",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "jammu_kashmir",
    name: "Jammu & Kashmir",
    nameHi: "जम्मू और कश्मीर",
    primaryLanguage: "Urdu",
    primaryLanguageCode: "ur",
    primaryLanguageNative: "اردو",
    ttsLocale: "ur-IN",
  },
  {
    id: "goa",
    name: "Goa",
    nameHi: "गोवा",
    primaryLanguage: "Konkani / Marathi",
    primaryLanguageCode: "mr",
    primaryLanguageNative: "कोंकणी / मराठी",
    ttsLocale: "mr-IN",
  },
  {
    id: "jharkhand",
    name: "Jharkhand",
    nameHi: "झारखंड",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
  {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    nameHi: "छत्तीसगढ़",
    primaryLanguage: "Hindi",
    primaryLanguageCode: "hi",
    primaryLanguageNative: "हिंदी",
    ttsLocale: "hi-IN",
  },
];
